graph LR;
    %% Styles
    classDef default fill:#F5F5F5,stroke:#333,stroke-width:1px,rx:5,ry:5;
    classDef hypothesis fill:#F8CECC,stroke:#333,stroke-width:1px,rx:5,ry:5;
    classDef future_work fill:#DAE8FC,stroke:#333,stroke-width:1px,rx:5,ry:5;

    %% Nodes
    Analyses_analysis_1["'<b><font size="5">analysis_1</font></b>'<br>Evaluating the overall financial and ... costs, and change in reservoir value."]
    Analyses_analysis_2["'<b><font size="5">analysis_2</font></b>'<br>Comparing the statistical properties and accuracy of the different price scenario inputs."]
    Analyses_analysis_3["'<b><font size="5">analysis_3</font></b>'<br>Observing operator behavior and ... bids during real-time operations."]
    Conclusions_conclusion_1["'<b><font size="5">conclusion_1</font></b>'<br>The stochastic method can largely ... constraints and boundary conditions."]
    Conclusions_conclusion_2["'<b><font size="5">conclusion_2</font></b>'<br>The authors conclude that the ensemble ... for resulting bids and schedules."]
    Conclusions_conclusion_3["'<b><font size="5">conclusion_3</font></b>'<br>Implementing a fully automated setup is ... the new method for it to be successful."]
    Experiments_experiment_1["'<b><font size="5">experiment_1</font></b>'<br>A rolling horizon counterfactual ... scenario inputs (ensemble and in-house)."]
    Experiments_experiment_2["'<b><font size="5">experiment_2</font></b>'<br>Real-time testing where operators were ... to choose which to submit to the market."]
    Future Work_suggested_hypothesis_1["'<b><font size="5">suggested_hypothesis_1</font></b>'<br>The authors hypothesise that including ... reservoirs and strict restrictions."]
    Future Work_suggested_research_question_1["'<b><font size="5">suggested_research_question_1</font></b>'<br>How can inflow uncertainty be effectively ... model to produce more robust bids?"]
    Future Work_suggested_research_question_2["'<b><font size="5">suggested_research_question_2</font></b>'<br>How can the underlying watercourse models ... crucial for scheduling decisions?"]
    Hypotheses_hypothesis_1["'<b><font size="5">hypothesis_1</font></b>'<br>Our hypothesis is that maintaining this ... and pressure head optimization."]
    Interpretations_interpretation_1["'<b><font size="5">interpretation_1</font></b>'<br>The stochastic-based models perform best ... (see final paragraph of section 5.5)."]
    Interpretations_interpretation_3["'<b><font size="5">interpretation_3</font></b>'<br>The ensemble scenarios perform better ... to rely on deterministic modelling alone."]
    Interpretations_interpretation_4["'<b><font size="5">interpretation_4</font></b>'<br>Operators were reluctant to use the ... plants, especially in complex cascades."]
    Research Questions_research_question_1["'<b><font size="5">research_question_1</font></b>'<br>How does a stochastic programming-based ... in day-ahead hydropower scheduling?"]
    Research Questions_research_question_2["'<b><font size="5">research_question_2</font></b>'<br>How does the method of generating price ... of the stochastic bidding model?"]

    subgraph Research Questions
        Research Questions_research_question_1
        Research Questions_research_question_2
    end

    subgraph Hypotheses
        Hypotheses_hypothesis_1
    end

    subgraph Experiments
        Experiments_experiment_1
        Experiments_experiment_2
    end

    subgraph Analyses
        Analyses_analysis_1
        Analyses_analysis_2
        Analyses_analysis_3
    end

    subgraph Interpretations
        Interpretations_interpretation_1
        Interpretations_interpretation_3
        Interpretations_interpretation_4
    end

    subgraph Conclusions
        Conclusions_conclusion_1
        Conclusions_conclusion_2
        Conclusions_conclusion_3
    end

    subgraph Future Work
        Future Work_suggested_research_question_1
        Future Work_suggested_research_question_2
        Future Work_suggested_hypothesis_1
    end

    %% Edges
    Analyses_analysis_1 --> Interpretations_interpretation_1
    Analyses_analysis_2 --> Interpretations_interpretation_3
    Analyses_analysis_3 --> Interpretations_interpretation_4
    Conclusions_conclusion_1 --> Future Work_suggested_hypothesis_1
    Conclusions_conclusion_1 --> Future Work_suggested_research_question_1
    Conclusions_conclusion_1 --> Future Work_suggested_research_question_2
    Conclusions_conclusion_1 --> Research Questions_research_question_1
    Conclusions_conclusion_2 --> Hypotheses_hypothesis_1
    Conclusions_conclusion_2 --> Research Questions_research_question_2
    Conclusions_conclusion_3 --> Future Work_suggested_hypothesis_1
    Conclusions_conclusion_3 --> Future Work_suggested_research_question_1
    Conclusions_conclusion_3 --> Future Work_suggested_research_question_2
    Conclusions_conclusion_3 --> Research Questions_research_question_1
    Experiments_experiment_1 --> Analyses_analysis_1
    Experiments_experiment_1 --> Analyses_analysis_2
    Experiments_experiment_2 --> Analyses_analysis_3
    Hypotheses_hypothesis_1 --> Experiments_experiment_1
    Interpretations_interpretation_1 --> Conclusions_conclusion_1
    Interpretations_interpretation_3 --> Conclusions_conclusion_3
    Research Questions_research_question_1 --> Experiments_experiment_1
    Research Questions_research_question_1 --> Experiments_experiment_2
    Research Questions_research_question_2 --> Experiments_experiment_1
    Research Questions_research_question_2 --> Hypotheses_hypothesis_1

    %% Styling
    class Research Questions_research_question_1 default
    class Research Questions_research_question_2 default
    class Hypotheses_hypothesis_1 hypothesis
    class Experiments_experiment_1 default
    class Experiments_experiment_2 default
    class Analyses_analysis_1 default
    class Analyses_analysis_2 default
    class Analyses_analysis_3 default
    class Interpretations_interpretation_1 default
    class Interpretations_interpretation_3 default
    class Interpretations_interpretation_4 default
    class Conclusions_conclusion_1 default
    class Conclusions_conclusion_2 default
    class Conclusions_conclusion_3 default
    class Future Work_suggested_research_question_1 future_work
    class Future Work_suggested_research_question_2 future_work
    class Future Work_suggested_hypothesis_1 future_work