graph LR;
    %% Styles
    classDef default fill:#F5F5F5,stroke:#333,stroke-width:1px,rx:5,ry:5;
    classDef hypothesis fill:#F8CECC,stroke:#333,stroke-width:1px,rx:5,ry:5;
    classDef future_work fill:#DAE8FC,stroke:#333,stroke-width:1px,rx:5,ry:5;

    %% Nodes
    Analyses_analysis_1["'<b><font size="5">analysis_1</font></b>'<br>Comparing the performance of the ... Gurobi configurations on MIPVerify."]
    Analyses_analysis_2["'<b><font size="5">analysis_2</font></b>'<br>Comparing the performance of the portfolio approach against default Venus configurations."]
    Conclusions_conclusion_1["'<b><font size="5">conclusion_1</font></b>'<br>The authors conclude that automated ... combinations accessible to the verifier.'"]
    Experiments_experiment_1["'<b><font size="5">experiment_1</font></b>'<br>Evaluating the constructed parallel MIP ... on the MIPVerify verification engine."]
    Experiments_experiment_2["'<b><font size="5">experiment_2</font></b>'<br>Evaluating the constructed parallel MIP ... on the Venus verification engine."]
    Future Work_suggested_research_question_1["'<b><font size="5">suggested_research_question_1</font></b>'<br>How can per-instance algorithm selection ... approach for neural network verification?"]
    Future Work_suggested_research_question_2["'<b><font size="5">suggested_research_question_2</font></b>'<br>How can hyperparameters at the ... on the MIP formulation and running time?"]
    Future Work_suggested_research_question_3["'<b><font size="5">suggested_research_question_3</font></b>'<br>Can heterogeneous portfolios containing ... in neural network verification?"]
    Hypotheses_hypothesis_1["'<b><font size="5">hypothesis_1</font></b>'<br>The authors hypothesise that constructing ... to be effective on the entire dataset."]
    Interpretations_interpretation_1["'<b><font size="5">interpretation_1</font></b>'<br>The authors interpret that for MIPVerify, ... smaller and easier to verify."]
    Interpretations_interpretation_2["'<b><font size="5">interpretation_2</font></b>'<br>The authors interpret that for Venus, the ... reported bounds on adversarial error."]
    Research Questions_research_question_1["'<b><font size="5">research_question_1</font></b>'<br>How can automated algorithm configuration ... network robustness verification tools?"]

    subgraph Research Questions
        Research Questions_research_question_1
    end

    subgraph Hypotheses
        Hypotheses_hypothesis_1
    end

    subgraph Experiments
        Experiments_experiment_1
        Experiments_experiment_2
    end

    subgraph Analyses
        Analyses_analysis_1
        Analyses_analysis_2
    end

    subgraph Interpretations
        Interpretations_interpretation_1
        Interpretations_interpretation_2
    end

    subgraph Conclusions
        Conclusions_conclusion_1
    end

    subgraph Future Work
        Future Work_suggested_research_question_1
        Future Work_suggested_research_question_2
        Future Work_suggested_research_question_3
    end

    %% Edges
    Analyses_analysis_1 --> Interpretations_interpretation_1
    Analyses_analysis_2 --> Interpretations_interpretation_2
    Conclusions_conclusion_1 --> Future Work_suggested_research_question_1
    Conclusions_conclusion_1 --> Future Work_suggested_research_question_2
    Conclusions_conclusion_1 --> Future Work_suggested_research_question_3
    Conclusions_conclusion_1 --> Hypotheses_hypothesis_1
    Conclusions_conclusion_1 --> Research Questions_research_question_1
    Experiments_experiment_1 --> Analyses_analysis_1
    Experiments_experiment_2 --> Analyses_analysis_2
    Hypotheses_hypothesis_1 --> Experiments_experiment_1
    Hypotheses_hypothesis_1 --> Experiments_experiment_2
    Interpretations_interpretation_1 --> Conclusions_conclusion_1
    Interpretations_interpretation_2 --> Conclusions_conclusion_1
    Research Questions_research_question_1 --> Experiments_experiment_1
    Research Questions_research_question_1 --> Experiments_experiment_2
    Research Questions_research_question_1 --> Hypotheses_hypothesis_1

    %% Styling
    class Research Questions_research_question_1 default
    class Hypotheses_hypothesis_1 hypothesis
    class Experiments_experiment_1 default
    class Experiments_experiment_2 default
    class Analyses_analysis_1 default
    class Analyses_analysis_2 default
    class Interpretations_interpretation_1 default
    class Interpretations_interpretation_2 default
    class Conclusions_conclusion_1 default
    class Future Work_suggested_research_question_1 future_work
    class Future Work_suggested_research_question_2 future_work
    class Future Work_suggested_research_question_3 future_work